export const dataSource : string = 'DATA_SOURCE';
export const userRepository : string = 'USER_REPOSITORY';
export const playerRepository : string = 'PLAYER_REPOSITORY';
export const scoreRepository : string = 'SCORE_REPOSITORY';
export const buyScoreRepository : string = 'BUYSCORE_REPOSITORY'
export const gameRepository : string = 'GAME_REPOSITORY';
export const questionRepository: string = 'QUESTION_REPOSITORY';
export const difficultyRepository: string = 'DIFFICULTY_REPOSITORY';
export const categoryRepository: string = 'CATEGORY_REPOSITORY';
export const answerRepository : string = 'ANSWER_REPOSITORY';